// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA800LZHSzuo6NDmUTIWUBtNQpADzX2Y7U',
    appId: '1:689136382346:web:6198bef854062d8b3d1873',
    messagingSenderId: '689136382346',
    projectId: 'kaamsetu-a4b04',
    authDomain: 'kaamsetu-a4b04.firebaseapp.com',
    storageBucket: 'kaamsetu-a4b04.firebasestorage.app',
    measurementId: 'G-92VDM1K8VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJolS-v7rQZW2Q_LHlK4xUe3G_tugBlg',
    appId: '1:689136382346:android:14d22c32d79c51833d1873',
    messagingSenderId: '689136382346',
    projectId: 'kaamsetu-a4b04',
    storageBucket: 'kaamsetu-a4b04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDuOehR8vqIzycTx5RQMYNSBaiUYGVTcI',
    appId: '1:689136382346:ios:17c110499be4f9093d1873',
    messagingSenderId: '689136382346',
    projectId: 'kaamsetu-a4b04',
    storageBucket: 'kaamsetu-a4b04.firebasestorage.app',
    iosBundleId: 'com.kaamsetu.kaamsetu',
  );
}
